[toolchain]
anchor_version = "0.32.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
trenches_hook = "4e59SgUgH6D8BaKbpq3CDRjdAJgoZg3Xm4tgzawpEA6Y"

[programs.devnet]
trenches_hook = "4e59SgUgH6D8BaKbpq3CDRjdAJgoZg3Xm4tgzawpEA6Y"

[provider]
cluster = "localnet"
wallet = ".local-keys/local.json"

[scripts]
test = "echo 'use: pnpm test (see README)'"
